### ISSUE TITLE
po-chart:  Erro na execução de teste

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1341]
#### Reprodução
![image](https://user-images.githubusercontent.com/36740857/179807928-048a6a3e-2002-4876-9604-a5124109469b.png)

![image](https://user-images.githubusercontent.com/36740857/179808096-fdefd38c-9b0b-4be0-850f-e231284c5efc.png)

Passos para reproduzir:
1.  `npm run test:ui` 

#### Qual o comportamento atual?
O teste está apresentando o erro:
```
        Error: Expected $.left = -75 to equal -77.
            at <Jasmine>
            at UserContext.apply (projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular-path/po-chart-tooltip.directive.spec.ts:120:22)
            at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:26)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:39)
Chrome Headless 103.0.5060.114 (Windows 10): Executed 3016 of 6485 (1 FAILED) (0 secs / 30.768 secs)
Chrome Headless 103.0.5060.114 (Windows 10) PoChartTooltipDirective Methods:  calculateTooltipPosition: should return tooltipPosition FAILED
        Error: Expected $.left = -75 to equal -77.
            at <Jasmine>
            at UserContext.apply (projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular-path/po-chart-tooltip.directive.spec.ts:120:22)
            at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:26)
```
#### Que comportamento você esperava ver?
Que o teste seja executado sem erro.

#### Ambiente

- PO UI: 14.0.0
- Angular: 14.0.2
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by wsteixeira** [comment]
Olá @jribeiroo,

Eu fiz um contribuição, mas passou a apresentar o erro invertido no linux-64:
`Error: Expected $.left = -77 to equal -75.`

Creio que o resultado do Win10 e linux-64 é diferente e por isso eu retirei a contribuição.
