### ISSUE TITLE
po-sync: Erro ao executar o método destroy() usando lokijs

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#1887]
#### Reprodução

Passos para reproduzir:
1. Criar um app utilizando o po-sync e configurar o po-storage para usar o lokijs.
2. Após inicializado a sincronização, executar o método destroy() para apagar todo o conteúdo.

#### Qual o comportamento atual?
Ocorre um erro no console
core.mjs:10614 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'lokiMap')
TypeError: Cannot read properties of undefined (reading 'lokiMap')
    at PoLokiDriver.getLokiMap (po-ui-ng-storage.mjs:188:61)
    at po-ui-ng-storage.mjs:106:38
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:11083:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at resolvePromise (zone.js:1193:31)
    at zone.js:1264:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:11070:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)
    at drainMicroTaskQueue (zone.js:581:35)

#### Que comportamento você esperava ver?
Execução do método sem erros como ocorre ao utilizar outros meios de armazenamento que não sejam o lokijs

#### Ambiente

- PO UI: 16.7.0
- Angular: 16.0.0
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações
Aparentemente o problema está na função getLokiMap() no fonte po-loki-driver.ts

**Comment by anliben** [comment]
Boa Tarde @likid, tudo bem?

Para podermos apoiá-lo precisaremos de mais detalhes para entender a situação

Utilize o Stackblitz para reproduzir o problema: https://stackblitz.com/edit/po-ui
Detalhe passo a passo a reprodução da ocorrência, inclua evidências utilizando imagens, vídeos ou gifs:
Passo 1...*
Passo 2...
Detalhe o comportamento atual:
Detalhe o comportamento que você espera ver:
Informe a versão dos ambientes:
PO UI: Ex. v15.8.0
Angular: Ex. 15
Node: Ex. 15
Informe o Browser:
[ ] Chrome
[ ] Firefox
[ ] Edge
[ ] Safari
[ ] IE 11
[ ] Outros
Informe e o Sistema Operacional:
[ ] Windows
[ ] macOS
[ ] Ubuntu
[ ] Outros
Aguardamos seu retorno!
