### ISSUE TITLE
Breadcrumb - componente na versão 17 com erro no link da Rota

### ISSUE THREAD

**Issue by ricardohmlsp** [po-ui/po-angular#1979]
Componente não faz o direcionamento correto não respeita a rota.
Tenho uma rota que aponta pro componente teste
url no navegador fica localhost:4200/teste -OK
ao acessar tenho um Breadcrumb da seguinte forma
 <po-breadcrumb
    [p-items]="[
      { label: 'Home', link: 'home' },
      { label: 'Teste',link: 'teste'}
    ]"
e clicar em Home ele tenta ir pra rota 
teste/home ao invez de apenas home

core.mjs:11754 ERROR Error: NG04002: Cannot match any routes. URL Segment: 'teste/home'
    at Recognizer.noMatchError (router.mjs:3646:12)
    at router.mjs:3679:20
    at catchError.js:10:39
    at OperatorSubscriber2._this._error (OperatorSubscriber.js:25:21)
    at Subscriber2.error (Subscriber.js:43:18)
    at Subscriber2._error (Subscriber.js:67:30)
    at Subscriber2.error (Subscriber.js:43:18)
    at Subscriber2._error (Subscriber.js:67:30)
    at Subscriber2.error (Subscriber.js:43:18)
    at Subscriber2._error (Subscriber.js:67:30)

#### Ambiente

- PO UI: 17
- Angular: 17.0.4
- Browser(s):
  - [ X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by anliben** [comment]
Boa Tarde @ricardohmlsp, tudo bem?

Para podermos apoiá-lo precisaremos de mais detalhes para entender a situação

- Utilize o Stackblitz para reproduzir o problema: https://stackblitz.com/edit/po-ui

### Detalhe passo a passo a reprodução da ocorrência, inclua evidências utilizando imagens, vídeos ou gifs:

- Passo 1...*
- Passo 2...
- Detalhe o comportamento atual:
- Detalhe o comportamento que você espera ver:

### Informe a versão dos ambientes:
- PO UI: Ex. v15.8.0
- Angular: Ex. 15
- Node: Ex. 15

### Informe o Browser:
- [ ] Chrome
- [ ]  Firefox
- [ ] Edge
- [ ]  Safari
 - [ ] IE 11
- [ ] Outros

### Informe e o Sistema Operacional:
- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Outros

### Aguardamos seu retorno!
