### ISSUE TITLE
PO UI com SSR

### ISSUE THREAD

**Issue by efdeiasoliveira** [po-ui/po-angular#2131]
#### Descrição da melhoria
Já existe alguma forma de trabalhar ou estudo voltado para trabalhar com SSR e PO UI na v17 do Angular ? 

#### Caso de uso
Quando crio um projeto Angular 17 com o PO UI e executo o ng serve ocorre o erro abaixo:

Error when evaluating SSR module /main.server.mjs:
|- ReferenceError: window is not defined
    at <static_initializer> (eval at instantiateModule (file:///Volumes/SAMSUNG%20320/totvs/poui/study/my-pets-v17/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:42675:36)
    at eval (eval at instantiateModule (file:///Volumes/SAMSUNG%20320/totvs/poui/study/my-pets-v17/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:42667:21)
    at async instantiateModule (file:///Volumes/SAMSUNG%20320/totvs/poui/study/my-pets-v17/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50861:9)

#### Informações adicionais
Somente gostariamos de saber se já há existe alguma forma de trabalhar com o SSR.

**Comment by fabiofurlanc** [comment]
estou com mesmo problema

**Comment by GAMELEIRA** [comment]
Sim isso também ocorre na versão 18.

**Comment by DiegoKenko** [comment]
também estou com o mesmo problema

**Comment by paixaocode** [comment]
mesmo problema por aqui

**Comment by DiegoKenko** [comment]
se for o caso, é possível configurar o projeto sem SSR. Pelo menos assim seu projeto irá rodar.

a issue https://github.com/po-ui/po-angular/issues/2013  mostra como configurar o projeto sem SSR.
