### ISSUE TITLE
<appShell>: Erro ao realizar a Build do Projeto utilizando AppShell e PO-Sync - ng run my-app:app-shell:production

### ISSUE THREAD

**Issue by nairansilva** [po-ui/po-angular#554]
#### Reprodução
Ao tentar realizar a Build de um projeto utilizando o PO-Sync com o App Shell, o seguinte erro é apresentado:
Unhandled Promise rejection: self is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: self is not defined
    at Object.<anonymous> (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:3002323)
    at __webpack_require__ (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2994247)
    at C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2994443
    at C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2994466
    at webpackUniversalModuleDefinition (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2993964)
    at Object.oAJy (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2993974)
    at __webpack_require__ (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:295)
    at Module.K011 (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2723463)
    at __webpack_require__ (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:295)
    at Object.0 (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:1733)
    at __webpack_require__ (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:295)
    at 0 (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:1624)
    at Object.<anonymous> (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:1669)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32) ReferenceError: self is not defined
    at Object.<anonymous> (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:3002323)
    at __webpack_require__ (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2994247)
    at C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2994443
    at C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2994466
    at webpackUniversalModuleDefinition (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2993964)
    at Object.oAJy (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2993974)
    at __webpack_require__ (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:295)
    at Module.K011 (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:2723463)
    at __webpack_require__ (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:295)
    at Object.0 (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:1733)
    at __webpack_require__ (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:295)
    at 0 (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:1624)
    at Object.<anonymous> (C:\Estudos WEB\teste PWA shell app\my-app\dist\my-app\server\main.js:1:1669)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
self is not defined

Passos para reproduzir:
1 - Seguir o passo-a-passo pra utilizar o App Shell do Angular.io (https://angular.io/guide/app-shell):
       - ng new my-app --routing
       - ng generate app-shell
2 - Adicionar os componentes do portinari (ng add @po-ui/ng-components);
3 - Adicionar o PO-Sync (ng add @po-ui/ng-sync);
4 - Buildar o Projeto com o App Shell: ng run my-app:app-shell:production

#### Qual o comportamento atual?
Erro no momento de gerar o Build do Projeto utilizando app shell

#### Que comportamento você esperava ver?
Build funcionando corretamente.

#### Ambiente

- PO UI: 3.0.0
- Angular: 10.0.5
- Browser(s):
  - [ X ] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ X ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhosefmarks** [comment]
@nairansilva vamos tentar analisar essa situação, não tivemos nenhuma experiência com PWA usando nosso componentes.

Estamos felizes e inspirados com esse primeiro caso.

**Comment by samir-ayoub** [comment]
Foram feitas as alterações necessárias para que não dê mais erro no console ao seguir o passo-a-passo reportado. 
Será liberado na v3.6.0.

**Comment by jhosefmarks** [comment]
Resolvido na PR: #599 

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#360-2020-09-14
